# Generated by Django 5.1.2 on 2024-11-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
    ]
