# Generated by Django 5.1.2 on 2024-11-27 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 27, 19, 28, 52, 416783, tzinfo=datetime.timezone.utc)),
        ),
    ]
