# Generated by Django 5.1.2 on 2024-12-10 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 10, 19, 34, 32, 437524, tzinfo=datetime.timezone.utc)),
        ),
    ]
