# Generated by Django 5.1.2 on 2024-12-23 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_user_date_joined_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 22, 29, 10, 432204, tzinfo=datetime.timezone.utc)),
        ),
    ]
