# Generated by Django 5.1.2 on 2024-12-23 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 22, 55, 57, 877115, tzinfo=datetime.timezone.utc)),
        ),
    ]
