# Generated by Django 5.1.2 on 2024-11-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_brand_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_file',
            field=models.ImageField(max_length=255, upload_to='product_images/%Y-%m-%d'),
        ),
    ]
