# Generated by Django 5.1.2 on 2024-12-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created', '-inventory']},
        ),
    ]
