# Generated by Django 5.1.2 on 2024-12-09 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created', '-inventory', 'price', 'off_percent', '-price']},
        ),
    ]
