# Generated by Django 5.1.2 on 2024-12-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_city_province_alter_order_city_city_province_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='province',
        ),
    ]
